### ISSUE TITLE
Forbidden: bot can't send messages to bots

### ISSUE THREAD

**Issue by hello4leaf** [3cky/jenkins-telegram-uploader-plugin#1]
![image](https://user-images.githubusercontent.com/11420861/47641360-329e6f00-dba9-11e8-85dc-90d68a4e427f.png)

{"ok":false,"error_code":403,"description":"Forbidden: bot can't send messages to bots"}

what is wrong

**Comment by 3cky** [comment]
Yep, telegram bots can't send messages to other bots by design, so you should specify chat ID of non-bot user, group or channel. You could obtain your account ID using [userinfobot](https://github.com/nadam/userinfobot) bot, just click start and it gives you your ID.
